import { useEffect, useRef, useState } from 'react';
import { ArrowRight, MapPin, MagnifyingGlass, Coffee, Plus, Minus, X, List, Clock, Check, Pause, Play, ShoppingBag } from '@phosphor-icons/react';
import { CoffeeScene } from './CoffeeScene.jsx';

const A='./assets/';
const products=[
 {id:'arabic-coffee',name:'Arabic Coffee',ar:'قهوة عربية',tag:'BOLD HERITAGE',artag:'أصالة في كل فنجان',price:2.50,kind:'Coffee',description:'A fragrant, gently spiced cup. Our tribute to Jordanian hospitality, served with a date.',ardesc:'قهوة عطرية بنكهة الهيل، تحتفي بالضيافة الأردنية وتُقدّم مع التمر.',options:['Hot']},
 {id:'pistachio-latte',name:'Pistachio Latte',ar:'لاتيه الفستق',tag:'SIGNATURE',artag:'من توقيعنا',price:4.25,kind:'Coffee',description:'Espresso, silky milk and a little pistachio indulgence. Finished with crushed pistachios.',ardesc:'إسبريسو مع الحليب الناعم والفستق، وتعلوه رشة من الفستق المجروش.',options:['Iced','Hot']},
 {id:'salted-caramel',name:'Salted Caramel',ar:'كراميل مملّح',tag:'SMOOTH & RICH',artag:'ناعم وغني',price:4.00,kind:'Coffee',description:'Rich espresso meets creamy caramel, with a pinch of sea salt and a generous whipped finish.',ardesc:'إسبريسو غني مع الكراميل الكريمي ولمسة ملح البحر، تعلوه الكريمة المخفوقة.',options:['Iced','Hot']},
 {id:'cold-brew',name:'Cold Brew',ar:'كولد برو',tag:'REFRESHING',artag:'انتعاش على مهلك',price:3.75,kind:'Cold',description:'Slow-steeped coffee, poured over ice. Clean, smooth and quietly bold.',ardesc:'قهوة منقوعة على البارد تُقدّم مع الثلج. مذاق ناعم وغني ومنعش.',options:['Iced']}
];
const locations=[{id:'jabal-amman',name:'Jabal Amman',ar:'جبل عمّان',street:'Rainbow St.',arstreet:'شارع الرينبو',hours:'7:00 AM – 11:00 PM',query:'Rainbow Street Amman Jordan'},{id:'abdali',name:'Abdali',ar:'العبدلي',street:'The Boulevard',arstreet:'البوليفارد',hours:'7:00 AM – 12:00 AM',query:'The Boulevard Abdali Amman Jordan'}];
const money=n=>`JOD ${n.toFixed(2)}`;
function Dialog({open,onClose,title,children,wide=false}){
 const ref=useRef();
 useEffect(()=>{const d=ref.current;if(open&&!d.open)d.showModal();if(!open&&d.open)d.close();document.body.classList.toggle('dialog-open',open);return()=>document.body.classList.remove('dialog-open');},[open]);
 return <dialog ref={ref} className={`dialog ${wide?'wide':''}`} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="dialog-shell"><header className="dialog-heading"><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={23}/></button></header>{children}</div></dialog>;
}
export function App(){
 const [ar,setAr]=useState(false),[mobileNav,setMobileNav]=useState(false),[modal,setModal]=useState(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[selected,setSelected]=useState(null),[temp,setTemp]=useState('Iced'),[quantity,setQuantity]=useState(1),[bag,setBag]=useState([]),[toast,setToast]=useState(''),[branch,setBranch]=useState('jabal-amman'),[name,setName]=useState(''),[ready,setReady]=useState(false),[motion,setMotion]=useState(()=>!matchMedia('(prefers-reduced-motion: reduce)').matches);
 const t=(en,arabic)=>ar?arabic:en;
 useEffect(()=>{document.documentElement.lang=ar?'ar':'en';},[ar]);
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),3000);return()=>clearTimeout(id);},[toast]);
 useEffect(()=>{document.body.classList.toggle('dialog-open',!!modal);return()=>document.body.classList.remove('dialog-open');},[modal]);
 const count=bag.reduce((s,p)=>s+p.quantity,0),total=bag.reduce((s,p)=>s+p.price*p.quantity,0);
 const close=()=>{setModal(null);setSelected(null);};
 function openMenu(search=false){setQuery('');setFilter('All');setSelected(null);setModal(search?'search':'menu');setMobileNav(false);}
 function details(p){setSelected(p);setTemp(p.options[0]);setQuantity(1);setModal('product');}
 function add(p,q=1,temperature=p.options[0]){setBag(items=>{const found=items.find(i=>i.id===p.id&&i.temperature===temperature);return found?items.map(i=>i===found?{...i,quantity:i.quantity+q}:i):[...items,{...p,quantity:q,temperature}];});setReady(false);setToast(t(`${p.name} added to your order`,`تمت إضافة ${p.ar} إلى طلبك`));}
 function change(index,delta){setBag(items=>items.map((p,i)=>i===index?{...p,quantity:p.quantity+delta}:p).filter(p=>p.quantity>0));setReady(false);}
 function navigate(id){document.getElementById(id)?.scrollIntoView({behavior:motion?'smooth':'auto'});setMobileNav(false);}
 const visible=products.filter(p=>(filter==='All'||(filter==='Cold'?p.options.includes('Iced'):p.kind===filter))&&`${p.name} ${p.ar} ${p.description}`.toLowerCase().includes(query.toLowerCase()));
 return <div className={`site ${ar?'arabic':''}`}>
 <a className="skip-link" href="#favorites">{t('Skip to menu','انتقل إلى القائمة')}</a>
 <main>
 <section className="hero" id="home" aria-label={t('Welcome to Qahwa Amman','أهلاً بك في قهوة عمّان')}>
  <CoffeeScene enabled={motion}/>
  <header className="site-header"><a href="#home" className="brand" aria-label="Qahwa Amman home"><img src={`${A}brand.webp`} alt="قهوة — Qahwa Amman" width="83" height="75"/></a>
   <nav className={`navigation ${mobileNav?'open':''}`} aria-label={t('Main navigation','القائمة الرئيسية')}><a className="active" href="#home" onClick={()=>setMobileNav(false)}>{t('Home','الرئيسية')}</a><button onClick={()=>openMenu()}>{t('Menu','القائمة')}</button><a href="#story" onClick={()=>setMobileNav(false)}>{t('Our Story','قصتنا')}</a><a href="#locations" onClick={()=>setMobileNav(false)}>{t('Locations','مواقعنا')}</a><button onClick={()=>{setModal('journal');setMobileNav(false);}}>{t('Journal','يومياتنا')}</button></nav>
   <div className="header-actions"><button className="language-button" onClick={()=>setAr(v=>!v)} aria-label={t('Switch to Arabic','Switch to English')}>{t('عربي','EN')}</button><span className="header-divider"/><button className="icon-button search-button" aria-label={t('Search the menu','ابحث في القائمة')} onClick={()=>openMenu(true)}><MagnifyingGlass size={24} weight="light"/></button><button className="button order-button" onClick={()=>{setModal('cart');setReady(false);}}><Coffee size={21} weight="light"/><span>{count?`${t('Your Order','طلبك')} (${count})`:t('Order Now','اطلب الآن')}</span></button><button className="icon-button mobile-toggle" aria-label={t('Toggle navigation','فتح القائمة')} aria-expanded={mobileNav} onClick={()=>setMobileNav(v=>!v)}>{mobileNav?<X size={25}/>:<List size={25}/>}</button></div>
  </header>
  <div className="hero-copy" dir={ar?'rtl':'ltr'}><div className="eyebrow">{t('AMMAN COFFEE HOUSE','بيت القهوة في عمّان')}</div><h1>{ar?<>قهوة تستحقّ<br/>أن تتمهّل لأجلها.</>:<>Coffee worth<br/>slowing down for.</>}</h1><p>{t('Exceptional coffee. Jordanian roots.','قهوة استثنائية. جذور أردنية.')}<br/>{t('A slower, kinder rhythm.','إيقاع أهدأ، ولحظات أجمل.')}</p><div className="hero-buttons"><button className="button" onClick={()=>openMenu()}>{t('Explore Menu','اكتشف القائمة')}<ArrowRight size={19} weight="light"/></button><button className="button outline" onClick={()=>navigate('locations')}><MapPin size={23}/>{t('Find Us','زورونا')}</button></div></div>
  <div className="hero-signature"><span className="short-line"/><p lang="ar" dir="rtl">قهوة ... لحظات أجمل</p><span>COFFEE FOR A BRIGHTER TOMORROW</span></div>
 </section>
 <section className="favorites" id="favorites" aria-labelledby="favorites-title"><div className="favorites-intro" dir={ar?'rtl':'ltr'}><div className="eyebrow">{t('FEATURED DRINKS','مشروباتنا المميّزة')}</div><h2 id="favorites-title">{ar?<>اختياراتنا<br/>المفضّلة</>:<>Our <br/>Favorites</>}</h2><span className="short-line"/><p>{t('A selection of drinks crafted with care,','مشروبات حضّرناها بعناية،')}<br/>{t('inspired by our home in Amman.','بإلهام من بيتنا في عمّان.')}</p><button className="text-link" onClick={()=>openMenu()}>{t('View Full Menu','شاهد القائمة كاملة')}<ArrowRight size={17}/></button></div>
  <div className="product-grid">{products.map(p=><article className="product-card" key={p.id}><button className="product-image" aria-label={t(`View ${p.name}`,`تفاصيل ${p.ar}`)} onClick={()=>details(p)}><img src={`${A}${p.id}.webp`} alt={t(p.name,p.ar)} width="191" height="148"/></button><div className="product-info"><button className="product-name" onClick={()=>details(p)}>{t(p.name,p.ar)}</button><p className="product-tag">{t(p.tag,p.artag)}</p><div className="price-row"><span>{money(p.price)}</span><button className="add-button" aria-label={t(`Add ${p.name} to order`,`أضف ${p.ar} إلى الطلب`)} onClick={()=>add(p)}><Plus size={19} weight="light"/></button></div></div></article>)}</div>
  <aside className="coffee-note" aria-label="Great coffee, brighter days"><img src={`${A}olive-branch.webp`} alt="" width="155" height="157"/><p>GREAT<br/>COFFEE<br/>BRIGHTER<br/>DAYS</p><span className="short-line"/></aside>
 </section>
 <div className="lower-grid"><section className="story-panel" id="story" aria-labelledby="story-title"><div className="story-copy" dir={ar?'rtl':'ltr'}><div className="eyebrow">{t('OUR STORY','قصتنا')}</div><h2 id="story-title">{t('Rooted in Amman.','جذورنا في عمّان.')}<br/>{t('Brewing for Good People.','وقهوتنا للناس الطيّبين.')}</h2><p>{t('Qahwa is more than a coffee house — it’s a meeting place for curious minds, good conversations, and a deeper appreciation for the little things.','قهوة أكثر من بيت للقهوة؛ هي مساحة للقاء، والأحاديث الجميلة، والاستمتاع بالتفاصيل الصغيرة.')}</p><button className="button small" onClick={()=>setModal('story')}>{t('Our Story','قصتنا')}<ArrowRight size={16}/></button></div></section>
  <section className="locations-panel" id="locations" aria-labelledby="locations-title" dir={ar?'rtl':'ltr'}><div className="eyebrow">{t('VISIT US','زورونا')}</div><h2 id="locations-title">{t('Our Locations','مواقعنا')}</h2><p className="locations-subtitle">{t('Two welcoming spaces in the heart of Amman.','مساحتان دافئتان في قلب عمّان.')}</p><button className="button small location-cta" onClick={()=>setModal('locations')}>{t('Find Your Nearest Qahwa','اختر قهوة الأقرب إلك')}<ArrowRight size={15}/></button><div className="location-cards">{locations.map(l=><button className="location-card" key={l.id} onClick={()=>{setBranch(l.id);setModal('locations');}}><img src={`${A}${l.id}.webp`} alt={t(l.name,l.ar)} width="120" height="80"/><span className="location-info"><strong>{t(l.name,l.ar)}</strong><span><MapPin size={15}/>{t(l.street,l.arstreet)}</span><span><Clock size={13}/><bdi>{l.hours}</bdi></span></span></button>)}</div></section></div>
 </main>
 <footer className="footer"><span>QAHWA AMMAN <span className="footer-dot">·</span> {t('Coffee for a brighter tomorrow.','قهوة ... لحظات أجمل')}</span>{import.meta.env.VITE_COFFEE_VIDEO_URL && <button className="motion-toggle" onClick={()=>setMotion(v=>!v)} aria-pressed={motion}>{motion?<Pause size={14}/>:<Play size={14}/>} {motion?t('Pause motion','إيقاف الحركة'):t('Play motion','تشغيل الحركة')}</button>}</footer>
 <div className={`toast ${toast?'visible':''}`} role="status" aria-live="polite"><Check size={18}/>{toast}<button onClick={()=>{setModal('cart');setToast('');}}>{t('View order','عرض الطلب')}</button></div>
 <Dialog open={modal==='menu'||modal==='search'} onClose={close} title={t('A little something for you.','على ذوقك، وعلى مهلك.')} wide><p className="dialog-description">{t('Good coffee, made your way.','قهوة طيبة، على كيفك.')}</p><div className="menu-tools"><label className="search-field"><MagnifyingGlass size={21}/><input autoFocus={modal==='search'} placeholder={t('Find your coffee…','ابحث عن قهوتك…')} value={query} onChange={e=>setQuery(e.target.value)} aria-label={t('Search drinks','بحث المشروبات')}/></label><div className="filter-tabs" role="group" aria-label="Drink category">{['All','Coffee','Cold'].map((f,i)=><button key={f} className={filter===f?'selected':''} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{t(f,['الكل','قهوة','بارد'][i])}</button>)}</div></div><div className="menu-list">{visible.map(p=><article className="menu-item" key={p.id}><button className="menu-item-image" onClick={()=>details(p)}><img src={`${A}${p.id}.webp`} alt={t(p.name,p.ar)}/></button><div><button className="menu-item-title" onClick={()=>details(p)}>{t(p.name,p.ar)}</button><p>{t(p.description,p.ardesc)}</p><span>{money(p.price)}</span></div><button className="add-button" aria-label={`Add ${p.name}`} onClick={()=>add(p)}><Plus size={19}/></button></article>)}</div>{!visible.length&&<div className="empty-state"><Coffee size={40} weight="light"/><h3>{t('No coffee by that name.','ما لقينا مشروب بهذا الاسم.')}</h3><button className="button" onClick={()=>{setQuery('');setFilter('All');}}>{t('See all drinks','كل المشروبات')}</button></div>}{!!count&&<button className="button full" onClick={()=>setModal('cart')}>{t('View your order','عرض طلبك')} ({count}) <span>{money(total)}</span><ArrowRight size={18}/></button>}</Dialog>
 <Dialog open={modal==='product'&&!!selected} onClose={close} title={selected?t(selected.name,selected.ar):''}>{selected&&<div className="detail"><img className="detail-image" src={`${A}${selected.id}.webp`} alt={t(selected.name,selected.ar)}/><p>{t(selected.description,selected.ardesc)}</p><div className="detail-options"><span>{t('Your preference','كيف بتحبّها؟')}</span><div className="filter-tabs">{selected.options.map(o=><button key={o} className={temp===o?'selected':''} aria-pressed={temp===o} onClick={()=>setTemp(o)}>{t(o,o==='Iced'?'باردة':'ساخنة')}</button>)}</div></div><div className="detail-options"><span>{t('Quantity','العدد')}</span><div className="quantity-control"><button aria-label="Decrease quantity" disabled={quantity===1} onClick={()=>setQuantity(n=>n-1)}><Minus size={16}/></button><span>{quantity}</span><button aria-label="Increase quantity" onClick={()=>setQuantity(n=>n+1)}><Plus size={16}/></button></div></div><button className="button full" onClick={()=>{add(selected,quantity,temp);close();}}>{t('Add to your order','أضف إلى طلبك')}<span>{money(selected.price*quantity)}</span></button></div>}</Dialog>
 <Dialog open={modal==='cart'} onClose={close} title={t('Your coffee moment.','وقت قهوتك.')}>
 {ready?<div className="empty-state success-state"><Check size={45} weight="light"/><h3>{t(`All set, ${name}.`,`طلبك جاهز للمعاينة، ${name}.`)}</h3><p>{t('Your order preview is ready. No order has been sent and no payment has been taken.','هذه معاينة لطلبك فقط. لم يتم إرسال الطلب أو تحصيل أي مبلغ.')}</p><p><strong>{t(locations.find(l=>l.id===branch).name,locations.find(l=>l.id===branch).ar)}</strong> · {count} {t('drinks','مشروبات')} · {money(total)}</p><button className="button" onClick={()=>setReady(false)}>{t('Back to order','العودة للطلب')}</button></div>:!bag.length?<div className="empty-state"><ShoppingBag size={44} weight="light"/><h3>{t('Something good is brewing.','قهوتك الطيبة بانتظارك.')}</h3><p>{t('Choose your favorites to start your order.','اختر مشروباتك المفضّلة لتجهيز طلبك.')}</p><button className="button" onClick={()=>openMenu()}>{t('Explore Menu','اكتشف القائمة')}<ArrowRight size={17}/></button></div>:<><div className="cart-items">{bag.map((p,i)=><article className="cart-item" key={`${p.id}-${p.temperature}`}><img src={`${A}${p.id}.webp`} alt={t(p.name,p.ar)}/><div className="cart-item-copy"><h3>{t(p.name,p.ar)}</h3><p>{t(p.temperature,p.temperature==='Hot'?'ساخنة':'باردة')} · {money(p.price)}</p><div className="quantity-control"><button aria-label={`Remove one ${p.name}`} onClick={()=>change(i,-1)}><Minus size={14}/></button><span>{p.quantity}</span><button aria-label={`Add one ${p.name}`} onClick={()=>change(i,1)}><Plus size={14}/></button></div></div><span>{money(p.price*p.quantity)}</span></article>)}</div><div className="order-total"><span>{t('Total','المجموع')}</span><strong>{money(total)}</strong></div><form className="order-form" onSubmit={e=>{e.preventDefault();setReady(true);}}><label>{t('Pick-up location','موقع الاستلام')}<select value={branch} onChange={e=>setBranch(e.target.value)}>{locations.map(l=><option key={l.id} value={l.id}>{t(l.name,l.ar)}</option>)}</select></label><label>{t('Your name','اسمك')}<input required value={name} onChange={e=>setName(e.target.value)} placeholder={t('First name','الاسم')} autoComplete="given-name" maxLength={60}/></label><p className="preview-note">{t('Preview only. Your order will not be sent to a café.','معاينة فقط. لن يتم إرسال الطلب إلى المقهى.')}</p><button className="button full" type="submit">{t('Preview order','معاينة الطلب')}<ArrowRight size={18}/></button></form></>}
 </Dialog>
 <Dialog open={modal==='story'} onClose={close} title={t('Rooted in Amman.','جذورنا في عمّان.')} wide><img className="story-dialog-image" src={`${A}story-clean.webp`} alt={t('The warm interior of Qahwa, with an olive tree and a stone coffee bar','أجواء قهوة الدافئة وشجرة الزيتون والبار الحجري')}/><div className="story-dialog-copy"><div className="eyebrow">{t('GOOD PEOPLE. BETTER COFFEE.','ناس طيّبة. وقهوة أطيب.')}</div><h3>{t('A place to take your time.','مكان تأخذ فيه وقتك.')}</h3><p>{t('In a city built on hills and hospitality, we believe a cup of coffee can bring us a little closer. To our roots. To one another. To the moments that make a day feel like our own.','في مدينة مبنية على الجبال والضيافة، نؤمن أن فنجان القهوة يقرّبنا من جذورنا، ومن بعضنا، ومن اللحظات التي تجعل يومنا أجمل.')}</p><p>{t('Come for your morning ritual, a good conversation, or a quiet corner. Stay a little longer. You’re always welcome at Qahwa.','تعال لقهوة الصباح، لحديث جميل، أو لركن هادئ. خذ راحتك. أهلاً وسهلاً في قهوة.')}</p><button className="button" onClick={()=>setModal('locations')}>{t('Come say hello','زورونا')}<ArrowRight size={17}/></button></div></Dialog>
 <Dialog open={modal==='locations'} onClose={close} title={t('Find your corner of Amman.','زاويتك الدافئة في عمّان.')} wide><p className="dialog-description">{t('Choose a neighborhood to explore the location.','اختر المنطقة لاستكشاف الموقع.')}</p><div className="location-dialog-grid">{locations.map(l=><article key={l.id} className={`branch-card ${branch===l.id?'selected':''}`}><img src={`${A}${l.id}.webp`} alt={t(l.name,l.ar)}/><div><h3>{t(l.name,l.ar)}</h3><p><MapPin size={17}/>{t(l.street,l.arstreet)}</p><p><Clock size={17}/><bdi>{l.hours}</bdi></p><a className="button" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(l.query)}`} target="_blank" rel="noreferrer">{t('Explore the area','استكشف المنطقة')}<ArrowRight size={16}/></a></div></article>)}</div><p className="preview-note">{t('Locations and opening hours follow the supplied design. Map links open the named area.','المواقع وساعات العمل حسب التصميم المرفق. روابط الخريطة تفتح المنطقة المذكورة.')}</p></Dialog>
 <Dialog open={modal==='journal'} onClose={close} title={t('Notes from the coffee house.','من يوميات قهوة.')} wide><div className="journal-grid"><img src={`${A}arabic-coffee.webp`} alt={t('Arabic coffee and a date','قهوة عربية مع التمر')}/><article><div className="eyebrow">{t('THE LITTLE RITUALS','طقوس صغيرة')}</div><h3>{t('The art of slowing down.','فنّ التمهّل.')}</h3><p>{t('Before the first sip, there is a moment: the aroma of cardamom, the warmth of the cup, the familiar sound of a friend arriving. Coffee is our invitation to notice it.','قبل الرشفة الأولى، هناك لحظة: رائحة الهيل، ودفء الفنجان، وصوت صديق يصل. القهوة دعوتنا لننتبه لهذه التفاصيل.')}</p><button className="text-link" onClick={()=>openMenu()}>{t('Find your daily ritual','اختر قهوتك اليومية')}<ArrowRight size={17}/></button></article></div></Dialog>
 </div>;
}
